import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1776685726544 implements MigrationInterface {
    name = 'InitialSchema1776685726544'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`warehouse\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`barcode\` varchar(255) NULL, \`productName\` varchar(255) NULL, \`modelCode\` varchar(255) NULL, \`lensColour\` varchar(255) NULL, \`madeBy\` varchar(255) NULL, \`model\` varchar(255) NULL, \`frameType\` varchar(255) NULL, \`category\` varchar(255) NULL, \`power\` varchar(255) NULL, \`colourCode\` varchar(255) NULL, \`colour\` varchar(255) NULL, \`brand\` varchar(255) NULL, \`taxGroup\` varchar(255) NULL, \`cost\` int NULL, \`rate\` int NULL, \`hsnCode\` varchar(255) NULL, \`nonStock\` tinyint NOT NULL DEFAULT 0, \`noOfSticker\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`barcode\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`encodedFormat\` varchar(255) NULL, \`printer\` varchar(255) NULL, \`fontSize\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`barcode_row\` (\`id\` int NOT NULL AUTO_INCREMENT, \`barcodeId\` int NOT NULL, \`startCharacter\` varchar(255) NULL, \`description\` varchar(255) NULL, \`type\` varchar(255) NULL, \`encode\` varchar(255) NULL, \`endCharacter\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendors\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`contactPerson\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`mobile\` varchar(255) NULL, \`email\` varchar(255) NULL, \`address\` varchar(255) NULL, \`place\` varchar(255) NULL, \`gstNumber\` varchar(255) NULL, \`tin\` varchar(255) NULL, \`website\` varchar(255) NULL, \`paymentTerms\` varchar(255) NULL, \`creditLimit\` int NOT NULL DEFAULT '0', \`dueDays\` int NOT NULL DEFAULT '0', \`openingBalance\` int NOT NULL DEFAULT '0', \`balanceType\` varchar(255) NOT NULL DEFAULT 'Debit', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stock_adjustment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`type\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tax_group\` (\`id\` int NOT NULL AUTO_INCREMENT, \`taxGroupCode\` varchar(255) NOT NULL, \`taxGroupName\` varchar(255) NOT NULL, \`taxPercent\` decimal(5,2) NOT NULL, \`cessPercent\` decimal(5,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`barcode\` varchar(255) NULL, \`productName\` varchar(255) NOT NULL, \`modelCode\` varchar(255) NULL, \`lensColour\` varchar(255) NULL, \`madeBy\` varchar(255) NULL, \`model\` varchar(255) NULL, \`frameType\` varchar(255) NULL, \`category\` varchar(255) NULL, \`power\` varchar(255) NULL, \`colourCode\` varchar(255) NULL, \`colour\` varchar(255) NULL, \`brand\` varchar(255) NULL, \`taxGroup\` varchar(255) NULL, \`cost\` int NULL, \`rate\` int NULL, \`hsnCode\` varchar(255) NULL, \`nonStock\` tinyint NOT NULL DEFAULT 0, \`noOfSticker\` int NULL, \`image\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stock\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branchId\` int NULL, \`productId\` int NULL, \`quantity\` int NOT NULL, \`vendor\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`damage\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product\` varchar(255) NOT NULL, \`reason\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`customerCode\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`branchId\` int NULL, \`type\` varchar(255) NOT NULL, \`openingBalance\` int NOT NULL DEFAULT '0', \`creditLimit\` int NULL, \`dueDays\` int NULL, \`gstNumber\` varchar(255) NULL, \`panNumber\` varchar(255) NULL, \`phone\` varchar(255) NOT NULL, \`mobile\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`place\` varchar(255) NULL, \`address\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`saleId\` int NOT NULL, \`productId\` int NOT NULL, \`quantity\` int NOT NULL, \`rate\` decimal(10,2) NOT NULL DEFAULT '0.00', \`tax\` decimal(10,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(10,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale\` (\`id\` int NOT NULL AUTO_INCREMENT, \`customerId\` int NOT NULL, \`branchId\` int NULL, \`invoiceNo\` varchar(255) NOT NULL, \`paymentMode\` varchar(255) NOT NULL, \`saleDate\` date NOT NULL, \`total\` decimal(10,2) NOT NULL, \`discount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`netTotal\` decimal(10,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_return_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`salesReturnId\` int NOT NULL, \`productId\` int NOT NULL, \`quantity\` int NOT NULL, \`rate\` decimal(10,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(10,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_return\` (\`id\` int NOT NULL AUTO_INCREMENT, \`customerId\` int NOT NULL, \`branchId\` int NULL, \`saleId\` int NULL, \`date\` date NOT NULL, \`total\` decimal(10,2) NOT NULL, \`reason\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`size\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sizeCode\` varchar(255) NOT NULL, \`sizeName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_order_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`salesOrderId\` int NOT NULL, \`productId\` int NOT NULL, \`quantity\` int NOT NULL, \`rate\` decimal NOT NULL, \`amount\` decimal NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_order\` (\`id\` int NOT NULL AUTO_INCREMENT, \`customerId\` int NOT NULL, \`branchId\` int NULL, \`date\` varchar(255) NOT NULL, \`total\` decimal NOT NULL DEFAULT '0', \`discount\` decimal NOT NULL DEFAULT '0', \`netTotal\` decimal NOT NULL DEFAULT '0', \`status\` varchar(255) NOT NULL DEFAULT 'Pending', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`eye_prescription\` (\`id\` int NOT NULL AUTO_INCREMENT, \`salesOrderId\` int NOT NULL, \`rightSphere\` varchar(255) NULL, \`rightCylinder\` varchar(255) NULL, \`rightAxis\` varchar(255) NULL, \`rightAdd\` varchar(255) NULL, \`leftSphere\` varchar(255) NULL, \`leftCylinder\` varchar(255) NULL, \`leftAxis\` varchar(255) NULL, \`leftAdd\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`salesman\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`branchId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_return\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branchId\` int NULL, \`invoiceNo\` varchar(255) NOT NULL, \`date\` varchar(255) NOT NULL, \`vendorId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_return_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`rate\` int NOT NULL, \`amount\` int NOT NULL, \`purchaseReturnId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`rate\` int NOT NULL, \`amount\` int NOT NULL, \`purchaseId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branchId\` int NULL, \`invoiceNo\` varchar(255) NOT NULL, \`date\` varchar(255) NOT NULL, \`paymentMode\` varchar(255) NOT NULL, \`vendorId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`period\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NULL, \`name\` varchar(255) NULL, \`fromDate\` date NULL, \`toDate\` date NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`power\` (\`id\` int NOT NULL AUTO_INCREMENT, \`powerCode\` varchar(255) NOT NULL, \`powerName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`patient\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cardNo\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`branchId\` int NULL, \`address\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`mobile\` varchar(255) NULL, \`email\` varchar(255) NULL, \`lensType\` varchar(255) NULL, \`doctor\` varchar(255) NULL, \`remark\` varchar(255) NULL, \`file\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lens_colour\` (\`id\` int NOT NULL AUTO_INCREMENT, \`lensColourCode\` varchar(255) NOT NULL, \`lensColourName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lens_order\` (\`id\` int NOT NULL AUTO_INCREMENT, \`customerName\` varchar(255) NOT NULL, \`branchId\` int NULL, \`phone\` varchar(255) NOT NULL, \`vendor\` varchar(255) NOT NULL, \`lensBrand\` varchar(255) NOT NULL, \`lensType\` varchar(255) NOT NULL, \`coating\` varchar(255) NOT NULL, \`rightSPH\` varchar(255) NULL, \`rightCYL\` varchar(255) NULL, \`rightAXIS\` varchar(255) NULL, \`leftSPH\` varchar(255) NULL, \`leftCYL\` varchar(255) NULL, \`leftAXIS\` varchar(255) NULL, \`status\` varchar(255) NOT NULL DEFAULT 'Pending', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`frame_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`frameTypeCode\` varchar(255) NOT NULL, \`frameTypeName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`eye_testing\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branchId\` int NULL, \`doctor\` varchar(255) NULL, \`date\` varchar(255) NULL, \`rightSphere\` varchar(255) NULL, \`rightCylinder\` varchar(255) NULL, \`rightAxis\` varchar(255) NULL, \`leftSphere\` varchar(255) NULL, \`leftCylinder\` varchar(255) NULL, \`leftAxis\` varchar(255) NULL, \`remark\` varchar(255) NULL, \`patientId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`model\` (\`id\` int NOT NULL AUTO_INCREMENT, \`modelCode\` varchar(255) NOT NULL, \`modelName\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`expiry\` tinyint NOT NULL DEFAULT 0, \`nonStockItem\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`made_by\` (\`id\` int NOT NULL AUTO_INCREMENT, \`madeByCode\` varchar(255) NOT NULL, \`madeByName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NULL, \`name\` varchar(255) NULL, \`subGroup\` varchar(255) NULL, \`under\` varchar(255) NULL, \`openingBalance\` decimal(12,2) NOT NULL DEFAULT '0.00', \`branchId\` int NULL, \`obType\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`journal_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`journalId\` int NOT NULL, \`accountId\` int NOT NULL, \`debit\` decimal(12,2) NOT NULL DEFAULT '0.00', \`credit\` decimal(12,2) NOT NULL DEFAULT '0.00', \`description\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`journal\` (\`id\` int NOT NULL AUTO_INCREMENT, \`entryNo\` varchar(255) NULL, \`date\` date NULL, \`reference\` varchar(255) NULL, \`description\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`doctor\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`branchId\` int NULL, \`address\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`mobile\` varchar(255) NULL, \`email\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`accountId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`colour_details\` (\`id\` int NOT NULL AUTO_INCREMENT, \`colourCode\` varchar(255) NOT NULL, \`colourName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_receipt\` (\`id\` int NOT NULL AUTO_INCREMENT, \`receiptNo\` varchar(255) NOT NULL, \`refNo\` varchar(255) NULL, \`branchId\` int NULL, \`date\` date NOT NULL, \`total\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category\` (\`id\` int NOT NULL AUTO_INCREMENT, \`categoryCode\` varchar(255) NOT NULL, \`categoryName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_receipt_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`receiptId\` int NOT NULL, \`customerId\` int NOT NULL, \`description\` varchar(255) NULL, \`amount\` int NOT NULL, \`discount\` int NOT NULL, \`net\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`colour_code\` (\`id\` int NOT NULL AUTO_INCREMENT, \`colourCode\` varchar(255) NOT NULL, \`colourName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_payment_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cashPaymentId\` int NOT NULL, \`debtorAccountId\` int NOT NULL, \`description\` varchar(255) NULL, \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash_payment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`paymentNo\` varchar(255) NULL, \`refNo\` varchar(255) NULL, \`branchId\` int NULL, \`date\` date NULL, \`creditorAccountId\` int NULL, \`totalAmount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`banking\` (\`id\` int NOT NULL AUTO_INCREMENT, \`bankName\` varchar(255) NULL, \`accountNumber\` varchar(255) NULL, \`branch\` varchar(255) NULL, \`accountId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brand\` (\`id\` int NOT NULL AUTO_INCREMENT, \`brandCode\` varchar(255) NOT NULL, \`brandName\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'Active', \`password\` varchar(255) NOT NULL DEFAULT 'password', \`role\` varchar(255) NOT NULL DEFAULT 'staff', \`branchId\` int NULL, UNIQUE INDEX \`IDX_840ac5cd67be99efa5cd989bf9\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_branch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`city\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`barcode_row\` ADD CONSTRAINT \`FK_349dcfe8a81c6aaa4edfdf97085\` FOREIGN KEY (\`barcodeId\`) REFERENCES \`barcode\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock\` ADD CONSTRAINT \`FK_e855a71c31948188c2bf78824a5\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_item\` ADD CONSTRAINT \`FK_59208ed392dd61056abbcf1482e\` FOREIGN KEY (\`saleId\`) REFERENCES \`sale\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_item\` ADD CONSTRAINT \`FK_d4361a12f11a57a6cf2a2ee6ac9\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale\` ADD CONSTRAINT \`FK_a742b91c1b99a4269c102d47541\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_return_item\` ADD CONSTRAINT \`FK_d128dcfc020775effa114d39a40\` FOREIGN KEY (\`salesReturnId\`) REFERENCES \`sales_return\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_return_item\` ADD CONSTRAINT \`FK_f9ca1eeaa7868d1a14f7e9262c3\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_return\` ADD CONSTRAINT \`FK_7faa5e4a601e97a799b90afa6ae\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_return\` ADD CONSTRAINT \`FK_3dfe1ccf87c564ab4280b643340\` FOREIGN KEY (\`saleId\`) REFERENCES \`sale\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_order_item\` ADD CONSTRAINT \`FK_e01b949632d690dbbcf5a60f15d\` FOREIGN KEY (\`salesOrderId\`) REFERENCES \`sales_order\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_order_item\` ADD CONSTRAINT \`FK_0f394562c9806bf1d706b5057a9\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_order\` ADD CONSTRAINT \`FK_612bd402fcea2b72502a478a76d\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_return\` ADD CONSTRAINT \`FK_2c57c3858a6f10a47bffa08d843\` FOREIGN KEY (\`vendorId\`) REFERENCES \`vendors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_return_item\` ADD CONSTRAINT \`FK_5fdf34672dd902e4b7cf64b1094\` FOREIGN KEY (\`purchaseReturnId\`) REFERENCES \`purchase_return\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_return_item\` ADD CONSTRAINT \`FK_75e414b5eeb65dcfbcf628dc9dc\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` ADD CONSTRAINT \`FK_29ba18d69c81231e8ffabe478b4\` FOREIGN KEY (\`purchaseId\`) REFERENCES \`purchase\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` ADD CONSTRAINT \`FK_0a3dd60e7f0694bbbc6bc301abb\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase\` ADD CONSTRAINT \`FK_e3f5fe271c0ce3c9a3f93124674\` FOREIGN KEY (\`vendorId\`) REFERENCES \`vendors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`eye_testing\` ADD CONSTRAINT \`FK_687c92866eb3e36152edd3fda14\` FOREIGN KEY (\`patientId\`) REFERENCES \`patient\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`journal_item\` ADD CONSTRAINT \`FK_6b0a80732375c635ea1d57f1d7e\` FOREIGN KEY (\`journalId\`) REFERENCES \`journal\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`journal_item\` ADD CONSTRAINT \`FK_ba4a543f6230cd994605d019a8a\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_payment_item\` ADD CONSTRAINT \`FK_8e71de16532eecffa870e25bf87\` FOREIGN KEY (\`cashPaymentId\`) REFERENCES \`cash_payment\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_payment_item\` ADD CONSTRAINT \`FK_f349a4bccb36c92a0f0198c8f43\` FOREIGN KEY (\`debtorAccountId\`) REFERENCES \`account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash_payment\` ADD CONSTRAINT \`FK_a8d5f3bfe9336036f99ce01dff2\` FOREIGN KEY (\`creditorAccountId\`) REFERENCES \`account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`banking\` ADD CONSTRAINT \`FK_0f6ff371b5e348ba814eea09556\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admin_user\` ADD CONSTRAINT \`FK_0bc695602386806aabca7e414fa\` FOREIGN KEY (\`branchId\`) REFERENCES \`admin_branch\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`admin_user\` DROP FOREIGN KEY \`FK_0bc695602386806aabca7e414fa\``);
        await queryRunner.query(`ALTER TABLE \`banking\` DROP FOREIGN KEY \`FK_0f6ff371b5e348ba814eea09556\``);
        await queryRunner.query(`ALTER TABLE \`cash_payment\` DROP FOREIGN KEY \`FK_a8d5f3bfe9336036f99ce01dff2\``);
        await queryRunner.query(`ALTER TABLE \`cash_payment_item\` DROP FOREIGN KEY \`FK_f349a4bccb36c92a0f0198c8f43\``);
        await queryRunner.query(`ALTER TABLE \`cash_payment_item\` DROP FOREIGN KEY \`FK_8e71de16532eecffa870e25bf87\``);
        await queryRunner.query(`ALTER TABLE \`journal_item\` DROP FOREIGN KEY \`FK_ba4a543f6230cd994605d019a8a\``);
        await queryRunner.query(`ALTER TABLE \`journal_item\` DROP FOREIGN KEY \`FK_6b0a80732375c635ea1d57f1d7e\``);
        await queryRunner.query(`ALTER TABLE \`eye_testing\` DROP FOREIGN KEY \`FK_687c92866eb3e36152edd3fda14\``);
        await queryRunner.query(`ALTER TABLE \`purchase\` DROP FOREIGN KEY \`FK_e3f5fe271c0ce3c9a3f93124674\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` DROP FOREIGN KEY \`FK_0a3dd60e7f0694bbbc6bc301abb\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item\` DROP FOREIGN KEY \`FK_29ba18d69c81231e8ffabe478b4\``);
        await queryRunner.query(`ALTER TABLE \`purchase_return_item\` DROP FOREIGN KEY \`FK_75e414b5eeb65dcfbcf628dc9dc\``);
        await queryRunner.query(`ALTER TABLE \`purchase_return_item\` DROP FOREIGN KEY \`FK_5fdf34672dd902e4b7cf64b1094\``);
        await queryRunner.query(`ALTER TABLE \`purchase_return\` DROP FOREIGN KEY \`FK_2c57c3858a6f10a47bffa08d843\``);
        await queryRunner.query(`ALTER TABLE \`sales_order\` DROP FOREIGN KEY \`FK_612bd402fcea2b72502a478a76d\``);
        await queryRunner.query(`ALTER TABLE \`sales_order_item\` DROP FOREIGN KEY \`FK_0f394562c9806bf1d706b5057a9\``);
        await queryRunner.query(`ALTER TABLE \`sales_order_item\` DROP FOREIGN KEY \`FK_e01b949632d690dbbcf5a60f15d\``);
        await queryRunner.query(`ALTER TABLE \`sales_return\` DROP FOREIGN KEY \`FK_3dfe1ccf87c564ab4280b643340\``);
        await queryRunner.query(`ALTER TABLE \`sales_return\` DROP FOREIGN KEY \`FK_7faa5e4a601e97a799b90afa6ae\``);
        await queryRunner.query(`ALTER TABLE \`sales_return_item\` DROP FOREIGN KEY \`FK_f9ca1eeaa7868d1a14f7e9262c3\``);
        await queryRunner.query(`ALTER TABLE \`sales_return_item\` DROP FOREIGN KEY \`FK_d128dcfc020775effa114d39a40\``);
        await queryRunner.query(`ALTER TABLE \`sale\` DROP FOREIGN KEY \`FK_a742b91c1b99a4269c102d47541\``);
        await queryRunner.query(`ALTER TABLE \`sale_item\` DROP FOREIGN KEY \`FK_d4361a12f11a57a6cf2a2ee6ac9\``);
        await queryRunner.query(`ALTER TABLE \`sale_item\` DROP FOREIGN KEY \`FK_59208ed392dd61056abbcf1482e\``);
        await queryRunner.query(`ALTER TABLE \`stock\` DROP FOREIGN KEY \`FK_e855a71c31948188c2bf78824a5\``);
        await queryRunner.query(`ALTER TABLE \`barcode_row\` DROP FOREIGN KEY \`FK_349dcfe8a81c6aaa4edfdf97085\``);
        await queryRunner.query(`DROP TABLE \`admin_branch\``);
        await queryRunner.query(`DROP INDEX \`IDX_840ac5cd67be99efa5cd989bf9\` ON \`admin_user\``);
        await queryRunner.query(`DROP TABLE \`admin_user\``);
        await queryRunner.query(`DROP TABLE \`brand\``);
        await queryRunner.query(`DROP TABLE \`banking\``);
        await queryRunner.query(`DROP TABLE \`cash_payment\``);
        await queryRunner.query(`DROP TABLE \`cash_payment_item\``);
        await queryRunner.query(`DROP TABLE \`colour_code\``);
        await queryRunner.query(`DROP TABLE \`cash_receipt_item\``);
        await queryRunner.query(`DROP TABLE \`category\``);
        await queryRunner.query(`DROP TABLE \`cash_receipt\``);
        await queryRunner.query(`DROP TABLE \`colour_details\``);
        await queryRunner.query(`DROP TABLE \`company\``);
        await queryRunner.query(`DROP TABLE \`doctor\``);
        await queryRunner.query(`DROP TABLE \`journal\``);
        await queryRunner.query(`DROP TABLE \`journal_item\``);
        await queryRunner.query(`DROP TABLE \`account\``);
        await queryRunner.query(`DROP TABLE \`made_by\``);
        await queryRunner.query(`DROP TABLE \`model\``);
        await queryRunner.query(`DROP TABLE \`eye_testing\``);
        await queryRunner.query(`DROP TABLE \`frame_type\``);
        await queryRunner.query(`DROP TABLE \`lens_order\``);
        await queryRunner.query(`DROP TABLE \`lens_colour\``);
        await queryRunner.query(`DROP TABLE \`patient\``);
        await queryRunner.query(`DROP TABLE \`power\``);
        await queryRunner.query(`DROP TABLE \`period\``);
        await queryRunner.query(`DROP TABLE \`purchase\``);
        await queryRunner.query(`DROP TABLE \`purchase_item\``);
        await queryRunner.query(`DROP TABLE \`purchase_return_item\``);
        await queryRunner.query(`DROP TABLE \`purchase_return\``);
        await queryRunner.query(`DROP TABLE \`salesman\``);
        await queryRunner.query(`DROP TABLE \`eye_prescription\``);
        await queryRunner.query(`DROP TABLE \`sales_order\``);
        await queryRunner.query(`DROP TABLE \`sales_order_item\``);
        await queryRunner.query(`DROP TABLE \`size\``);
        await queryRunner.query(`DROP TABLE \`sales_return\``);
        await queryRunner.query(`DROP TABLE \`sales_return_item\``);
        await queryRunner.query(`DROP TABLE \`sale\``);
        await queryRunner.query(`DROP TABLE \`sale_item\``);
        await queryRunner.query(`DROP TABLE \`customer\``);
        await queryRunner.query(`DROP TABLE \`damage\``);
        await queryRunner.query(`DROP TABLE \`stock\``);
        await queryRunner.query(`DROP TABLE \`product\``);
        await queryRunner.query(`DROP TABLE \`tax_group\``);
        await queryRunner.query(`DROP TABLE \`stock_adjustment\``);
        await queryRunner.query(`DROP TABLE \`vendors\``);
        await queryRunner.query(`DROP TABLE \`barcode_row\``);
        await queryRunner.query(`DROP TABLE \`barcode\``);
        await queryRunner.query(`DROP TABLE \`warehouse\``);
    }

}
